2017-06-25 09:54:54,667 [Thread-9:9448] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-06-25 10:03:56,701 [Thread-17:8128] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\mypro\flxm\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\mypro\flxm\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\sites.py", line 413, in login
    return login(request, **defaults)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\auth\views.py", line 49, in inner
    return func(*args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\views\decorators\debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\auth\views.py", line 76, in login
    auth_login(request, form.get_user())
  File "C:\mypro\flxm\lib\site-packages\django\contrib\auth\__init__.py", line 110, in login
    request.session.cycle_key()
  File "C:\mypro\flxm\lib\site-packages\django\contrib\sessions\backends\base.py", line 302, in cycle_key
    self.create()
  File "C:\mypro\flxm\lib\site-packages\django\contrib\sessions\backends\db.py", line 49, in create
    self._session_key = self._get_new_session_key()
  File "C:\mypro\flxm\lib\site-packages\django\contrib\sessions\backends\base.py", line 155, in _get_new_session_key
    if not self.exists(session_key):
  File "C:\mypro\flxm\lib\site-packages\django\contrib\sessions\backends\db.py", line 45, in exists
    return self.model.objects.filter(session_key=session_key).exists()
  File "C:\mypro\flxm\lib\site-packages\django\db\models\query.py", line 651, in exists
    return self.query.has_results(using=self.db)
  File "C:\mypro\flxm\lib\site-packages\django\db\models\sql\query.py", line 501, in has_results
    return compiler.has_results()
  File "C:\mypro\flxm\lib\site-packages\django\db\models\sql\compiler.py", line 819, in has_results
    return bool(self.execute_sql(SINGLE))
  File "C:\mypro\flxm\lib\site-packages\django\db\models\sql\compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "C:\mypro\flxm\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\mypro\flxm\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\mypro\flxm\lib\site-packages\django\db\utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\mypro\flxm\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\mypro\flxm\lib\site-packages\django\db\backends\mysql\base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "C:\mypro\flxm\lib\site-packages\pymysql\cursors.py", line 158, in execute
    result = self._query(query)
  File "C:\mypro\flxm\lib\site-packages\pymysql\cursors.py", line 308, in _query
    conn.query(q)
  File "C:\mypro\flxm\lib\site-packages\pymysql\connections.py", line 820, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\mypro\flxm\lib\site-packages\pymysql\connections.py", line 1002, in _read_query_result
    result.read()
  File "C:\mypro\flxm\lib\site-packages\pymysql\connections.py", line 1285, in read
    first_packet = self.connection._read_packet()
  File "C:\mypro\flxm\lib\site-packages\pymysql\connections.py", line 966, in _read_packet
    packet.check_error()
  File "C:\mypro\flxm\lib\site-packages\pymysql\connections.py", line 394, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\mypro\flxm\lib\site-packages\pymysql\err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "C:\mypro\flxm\lib\site-packages\pymysql\err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
ProgrammingError: (1146, u"Table 'flaccdb.django_session' doesn't exist")
2017-06-25 10:06:59,296 [Thread-19:7032] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-06-25 10:07:15,410 [Thread-29:3980] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\mypro\flxm\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\mypro\flxm\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\sites.py", line 413, in login
    return login(request, **defaults)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\auth\views.py", line 49, in inner
    return func(*args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\views\decorators\debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\auth\views.py", line 76, in login
    auth_login(request, form.get_user())
  File "C:\mypro\flxm\lib\site-packages\django\contrib\auth\__init__.py", line 110, in login
    request.session.cycle_key()
  File "C:\mypro\flxm\lib\site-packages\django\contrib\sessions\backends\base.py", line 302, in cycle_key
    self.create()
  File "C:\mypro\flxm\lib\site-packages\django\contrib\sessions\backends\db.py", line 49, in create
    self._session_key = self._get_new_session_key()
  File "C:\mypro\flxm\lib\site-packages\django\contrib\sessions\backends\base.py", line 155, in _get_new_session_key
    if not self.exists(session_key):
  File "C:\mypro\flxm\lib\site-packages\django\contrib\sessions\backends\db.py", line 45, in exists
    return self.model.objects.filter(session_key=session_key).exists()
  File "C:\mypro\flxm\lib\site-packages\django\db\models\query.py", line 651, in exists
    return self.query.has_results(using=self.db)
  File "C:\mypro\flxm\lib\site-packages\django\db\models\sql\query.py", line 501, in has_results
    return compiler.has_results()
  File "C:\mypro\flxm\lib\site-packages\django\db\models\sql\compiler.py", line 819, in has_results
    return bool(self.execute_sql(SINGLE))
  File "C:\mypro\flxm\lib\site-packages\django\db\models\sql\compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "C:\mypro\flxm\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\mypro\flxm\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\mypro\flxm\lib\site-packages\django\db\utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\mypro\flxm\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\mypro\flxm\lib\site-packages\django\db\backends\mysql\base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "C:\mypro\flxm\lib\site-packages\pymysql\cursors.py", line 158, in execute
    result = self._query(query)
  File "C:\mypro\flxm\lib\site-packages\pymysql\cursors.py", line 308, in _query
    conn.query(q)
  File "C:\mypro\flxm\lib\site-packages\pymysql\connections.py", line 820, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\mypro\flxm\lib\site-packages\pymysql\connections.py", line 1002, in _read_query_result
    result.read()
  File "C:\mypro\flxm\lib\site-packages\pymysql\connections.py", line 1285, in read
    first_packet = self.connection._read_packet()
  File "C:\mypro\flxm\lib\site-packages\pymysql\connections.py", line 966, in _read_packet
    packet.check_error()
  File "C:\mypro\flxm\lib\site-packages\pymysql\connections.py", line 394, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\mypro\flxm\lib\site-packages\pymysql\err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "C:\mypro\flxm\lib\site-packages\pymysql\err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
ProgrammingError: (1146, u"Table 'flaccdb.django_session' doesn't exist")
2017-06-25 17:43:17,838 [Thread-3:9008] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-06-25 17:43:28,729 [Thread-9:8876] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-06-25 17:43:33,594 [Thread-10:9912] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/Acc/rzxx/add/
Traceback (most recent call last):
  File "C:\mypro\flxm\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\mypro\flxm\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 1437, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 1367, in changeform_view
    ModelForm = self.get_form(request, obj)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 642, in get_form
    % (e, self.__class__.__name__))
FieldError: Unknown field(s) (rzsj) specified for Rzxx. Check fields/fieldsets/exclude attributes of class RzxxAdmin.
2017-06-25 17:46:59,759 [Thread-2:8880] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/Acc/rzxx/add/
Traceback (most recent call last):
  File "C:\mypro\flxm\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\mypro\flxm\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 1437, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 1367, in changeform_view
    ModelForm = self.get_form(request, obj)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 642, in get_form
    % (e, self.__class__.__name__))
FieldError: Unknown field(s) (rzsj) specified for Rzxx. Check fields/fieldsets/exclude attributes of class RzxxAdmin.
2017-06-25 21:14:29,121 [Thread-2:944] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/Acc/rzxx/add/
Traceback (most recent call last):
  File "C:\mypro\flxm\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\mypro\flxm\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 1437, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 1367, in changeform_view
    ModelForm = self.get_form(request, obj)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 642, in get_form
    % (e, self.__class__.__name__))
FieldError: Unknown field(s) (rzsj) specified for Rzxx. Check fields/fieldsets/exclude attributes of class RzxxAdmin.
2017-06-25 22:00:27,474 [Thread-2:8348] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/Acc/rzxx/add/
Traceback (most recent call last):
  File "C:\mypro\flxm\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\mypro\flxm\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 1437, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 1367, in changeform_view
    ModelForm = self.get_form(request, obj)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 642, in get_form
    % (e, self.__class__.__name__))
FieldError: Unknown field(s) (rzsj) specified for Rzxx. Check fields/fieldsets/exclude attributes of class RzxxAdmin.
2017-06-25 22:01:39,476 [Thread-4:9916] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/Acc/rzxx/add/
Traceback (most recent call last):
  File "C:\mypro\flxm\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\mypro\flxm\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 1437, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\mypro\flxm\lib\site-packages\django\utils\decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 1367, in changeform_view
    ModelForm = self.get_form(request, obj)
  File "C:\mypro\flxm\lib\site-packages\django\contrib\admin\options.py", line 642, in get_form
    % (e, self.__class__.__name__))
FieldError: Unknown field(s) (rzsj) specified for Rzxx. Check fields/fieldsets/exclude attributes of class RzxxAdmin.
